//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class act_activities
    {
        public int id_act { get; set; }
        public string activity_name { get; set; }
        public Nullable<int> designer { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> ecd { get; set; }
        public Nullable<System.DateTime> completed { get; set; }
        public string description { get; set; }
        public Nullable<int> id_acti { get; set; }
        public Nullable<double> hours { get; set; }
        public Nullable<int> phase { get; set; }
        public Nullable<int> team { get; set; }
    
        public virtual owners owners { get; set; }
        public virtual fup_phases fup_phases { get; set; }
        public virtual master_activities master_activities { get; set; }
        public virtual teams teams { get; set; }
    }
}
