//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class acti_months
    {
        public int id_rel { get; set; }
        public Nullable<int> id_acti { get; set; }
        public string month_year { get; set; }
    
        public virtual master_activities master_activities { get; set; }
    }
}
