//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class function_list
    {
        public int id_list { get; set; }
        public Nullable<int> id_tecno_brick { get; set; }
        public Nullable<int> id_function { get; set; }
        public Nullable<int> id_tecno_stream { get; set; }
    
        public virtual tecno_bricks tecno_bricks { get; set; }
        public virtual tecno_function tecno_function { get; set; }
        public virtual tecno_stream tecno_stream { get; set; }
    }
}
