//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark_focus
    {
        public mark_focus()
        {
            this.focus_list = new HashSet<focus_list>();
            this.table_project_mark_bricks = new HashSet<table_project_mark_bricks>();
        }
    
        public int id_focus { get; set; }
        public string focus_name { get; set; }
    
        public virtual ICollection<focus_list> focus_list { get; set; }
        public virtual ICollection<table_project_mark_bricks> table_project_mark_bricks { get; set; }
    }
}
