//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark_bricks
    {
        public mark_bricks()
        {
            this.focus_list = new HashSet<focus_list>();
            this.table_project_mark_bricks = new HashSet<table_project_mark_bricks>();
        }
    
        public int id_mark_brick { get; set; }
        public string project_name { get; set; }
        public string seat_class { get; set; }
        public string mark_contact { get; set; }
        public Nullable<int> image_id { get; set; }
        public Nullable<int> presentation_id { get; set; }
        public string mark_description { get; set; }
        public Nullable<int> brick_num { get; set; }
    
        public virtual ICollection<focus_list> focus_list { get; set; }
        public virtual follow_files follow_files { get; set; }
        public virtual follow_files follow_files1 { get; set; }
        public virtual ICollection<table_project_mark_bricks> table_project_mark_bricks { get; set; }
    }
}
