//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class followupEntities : DbContext
    {
        public followupEntities()
            : base("name=followupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<owners> owners { get; set; }
        public DbSet<act_activities> act_activities { get; set; }
        public DbSet<act_budget> act_budget { get; set; }
        public DbSet<act_team> act_team { get; set; }
        public DbSet<acti_months> acti_months { get; set; }
        public DbSet<activities> activities { get; set; }
        public DbSet<budget> budget { get; set; }
        public DbSet<budget_costs> budget_costs { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<focus_list> focus_list { get; set; }
        public DbSet<follow_files> follow_files { get; set; }
        public DbSet<function_list> function_list { get; set; }
        public DbSet<fund_activities> fund_activities { get; set; }
        public DbSet<fund_budget> fund_budget { get; set; }
        public DbSet<fundvscluster> fundvscluster { get; set; }
        public DbSet<fup_phases> fup_phases { get; set; }
        public DbSet<leader> leader { get; set; }
        public DbSet<mark_bricks> mark_bricks { get; set; }
        public DbSet<mark_focus> mark_focus { get; set; }
        public DbSet<master_activities> master_activities { get; set; }
        public DbSet<master_followup> master_followup { get; set; }
        public DbSet<master_fund> master_fund { get; set; }
        public DbSet<master_uni> master_uni { get; set; }
        public DbSet<program_man> program_man { get; set; }
        public DbSet<programs_months> programs_months { get; set; }
        public DbSet<projectvsclusters> projectvsclusters { get; set; }
        public DbSet<seat_class> seat_class { get; set; }
        public DbSet<site> site { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<sub_category> sub_category { get; set; }
        public DbSet<support_type> support_type { get; set; }
        public DbSet<table_project_mark_bricks> table_project_mark_bricks { get; set; }
        public DbSet<table_project_rd> table_project_rd { get; set; }
        public DbSet<table_project_tecno_bricks> table_project_tecno_bricks { get; set; }
        public DbSet<teams> teams { get; set; }
        public DbSet<tecno_bricks> tecno_bricks { get; set; }
        public DbSet<tecno_budget> tecno_budget { get; set; }
        public DbSet<tecno_comments> tecno_comments { get; set; }
        public DbSet<tecno_function> tecno_function { get; set; }
        public DbSet<tecno_months> tecno_months { get; set; }
        public DbSet<tecno_obj_list> tecno_obj_list { get; set; }
        public DbSet<tecno_objs> tecno_objs { get; set; }
        public DbSet<tecno_stream> tecno_stream { get; set; }
        public DbSet<toolvscluster> toolvscluster { get; set; }
        public DbSet<uni_activities> uni_activities { get; set; }
        public DbSet<uni_budget> uni_budget { get; set; }
        public DbSet<uni_months> uni_months { get; set; }
        public DbSet<univsclusters> univsclusters { get; set; }
        public DbSet<comments> comments { get; set; }
        public DbSet<mark_comments> mark_comments { get; set; }
    }
}
