//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class site
    {
        public site()
        {
            this.act_budget = new HashSet<act_budget>();
            this.budget = new HashSet<budget>();
            this.fund_budget = new HashSet<fund_budget>();
            this.leader = new HashSet<leader>();
            this.master_activities = new HashSet<master_activities>();
            this.master_followup = new HashSet<master_followup>();
            this.master_fund = new HashSet<master_fund>();
            this.master_uni = new HashSet<master_uni>();
            this.program_man = new HashSet<program_man>();
            this.tecno_bricks = new HashSet<tecno_bricks>();
            this.tecno_bricks1 = new HashSet<tecno_bricks>();
            this.tecno_budget = new HashSet<tecno_budget>();
            this.uni_budget = new HashSet<uni_budget>();
        }
    
        public int id_site { get; set; }
        public string site_name { get; set; }
    
        public virtual ICollection<act_budget> act_budget { get; set; }
        public virtual ICollection<budget> budget { get; set; }
        public virtual ICollection<fund_budget> fund_budget { get; set; }
        public virtual ICollection<leader> leader { get; set; }
        public virtual ICollection<master_activities> master_activities { get; set; }
        public virtual ICollection<master_followup> master_followup { get; set; }
        public virtual ICollection<master_fund> master_fund { get; set; }
        public virtual ICollection<master_uni> master_uni { get; set; }
        public virtual ICollection<program_man> program_man { get; set; }
        public virtual ICollection<tecno_bricks> tecno_bricks { get; set; }
        public virtual ICollection<tecno_bricks> tecno_bricks1 { get; set; }
        public virtual ICollection<tecno_budget> tecno_budget { get; set; }
        public virtual ICollection<uni_budget> uni_budget { get; set; }
    }
}
