//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_project_mark_bricks
    {
        public int id_list { get; set; }
        public Nullable<int> id_project { get; set; }
        public Nullable<int> id_mark_brick { get; set; }
        public Nullable<int> id_focus { get; set; }
    
        public virtual mark_bricks mark_bricks { get; set; }
        public virtual mark_focus mark_focus { get; set; }
        public virtual master_followup master_followup { get; set; }
    }
}
