//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecno_function
    {
        public tecno_function()
        {
            this.function_list = new HashSet<function_list>();
            this.table_project_tecno_bricks = new HashSet<table_project_tecno_bricks>();
        }
    
        public int id_function { get; set; }
        public string function_name { get; set; }
        public Nullable<int> id_tecno_stream { get; set; }
    
        public virtual ICollection<function_list> function_list { get; set; }
        public virtual ICollection<table_project_tecno_bricks> table_project_tecno_bricks { get; set; }
        public virtual tecno_stream tecno_stream { get; set; }
    }
}
