//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecno_objs
    {
        public tecno_objs()
        {
            this.fundvscluster = new HashSet<fundvscluster>();
            this.projectvsclusters = new HashSet<projectvsclusters>();
            this.tecno_obj_list = new HashSet<tecno_obj_list>();
            this.univsclusters = new HashSet<univsclusters>();
            this.toolvscluster = new HashSet<toolvscluster>();
        }
    
        public int id_tecno_obj { get; set; }
        public string tecno_obj_name { get; set; }
    
        public virtual ICollection<fundvscluster> fundvscluster { get; set; }
        public virtual ICollection<projectvsclusters> projectvsclusters { get; set; }
        public virtual ICollection<tecno_obj_list> tecno_obj_list { get; set; }
        public virtual ICollection<univsclusters> univsclusters { get; set; }
        public virtual ICollection<toolvscluster> toolvscluster { get; set; }
    }
}
