//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecno_stream
    {
        public tecno_stream()
        {
            this.function_list = new HashSet<function_list>();
            this.tecno_function = new HashSet<tecno_function>();
        }
    
        public int id_tecno_stream { get; set; }
        public string tecno_stream_name { get; set; }
    
        public virtual ICollection<function_list> function_list { get; set; }
        public virtual ICollection<tecno_function> tecno_function { get; set; }
    }
}
