//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecno_bricks
    {
        public tecno_bricks()
        {
            this.function_list = new HashSet<function_list>();
            this.table_project_tecno_bricks = new HashSet<table_project_tecno_bricks>();
            this.tecno_budget = new HashSet<tecno_budget>();
            this.tecno_comments = new HashSet<tecno_comments>();
            this.tecno_months = new HashSet<tecno_months>();
            this.tecno_obj_list = new HashSet<tecno_obj_list>();
        }
    
        public int id_tecno_brick { get; set; }
        public Nullable<int> site { get; set; }
        public string project_name { get; set; }
        public string project_reference { get; set; }
        public string lead { get; set; }
        public Nullable<int> image_id { get; set; }
        public string material { get; set; }
        public Nullable<int> seat_class { get; set; }
        public Nullable<int> sub_assy { get; set; }
        public Nullable<int> funded_by { get; set; }
        public string plan_budget { get; set; }
        public string actual_budget { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> trl1 { get; set; }
        public Nullable<System.DateTime> trl2 { get; set; }
        public Nullable<System.DateTime> trl3 { get; set; }
        public Nullable<System.DateTime> trl4 { get; set; }
        public Nullable<System.DateTime> trl5 { get; set; }
        public Nullable<System.DateTime> trl6 { get; set; }
        public Nullable<System.DateTime> trl7 { get; set; }
        public Nullable<System.DateTime> trl8 { get; set; }
        public Nullable<int> trl1_id { get; set; }
        public Nullable<int> trl2_id { get; set; }
        public Nullable<int> trl3_id { get; set; }
        public Nullable<int> trl4_id { get; set; }
        public Nullable<int> trl5_id { get; set; }
        public Nullable<int> trl6_id { get; set; }
        public Nullable<int> trl7_id { get; set; }
        public Nullable<int> trl8_id { get; set; }
        public string tecno_scope { get; set; }
        public string tecno_deli { get; set; }
        public Nullable<int> brick_num { get; set; }
        public Nullable<int> duration_month { get; set; }
        public string number_months { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> supp_type { get; set; }
        public string zen_link { get; set; }
    
        public virtual follow_files follow_files { get; set; }
        public virtual follow_files follow_files1 { get; set; }
        public virtual follow_files follow_files2 { get; set; }
        public virtual follow_files follow_files3 { get; set; }
        public virtual follow_files follow_files4 { get; set; }
        public virtual follow_files follow_files5 { get; set; }
        public virtual follow_files follow_files6 { get; set; }
        public virtual follow_files follow_files7 { get; set; }
        public virtual follow_files follow_files8 { get; set; }
        public virtual ICollection<function_list> function_list { get; set; }
        public virtual seat_class seat_class1 { get; set; }
        public virtual site site1 { get; set; }
        public virtual site site2 { get; set; }
        public virtual status status1 { get; set; }
        public virtual sub_category sub_category { get; set; }
        public virtual support_type support_type { get; set; }
        public virtual ICollection<table_project_tecno_bricks> table_project_tecno_bricks { get; set; }
        public virtual ICollection<tecno_budget> tecno_budget { get; set; }
        public virtual ICollection<tecno_comments> tecno_comments { get; set; }
        public virtual ICollection<tecno_months> tecno_months { get; set; }
        public virtual ICollection<tecno_obj_list> tecno_obj_list { get; set; }
    }
}
