//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecno_comments
    {
        public int id_comment { get; set; }
        public Nullable<int> id_tecno_brick { get; set; }
        public string user_name { get; set; }
        public string prefix { get; set; }
        public string comment { get; set; }
        public Nullable<int> file_id { get; set; }
        public Nullable<System.DateTime> comment_date { get; set; }
    
        public virtual follow_files follow_files { get; set; }
        public virtual tecno_bricks tecno_bricks { get; set; }
    }
}
