//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tecno_obj_list
    {
        public int id_list { get; set; }
        public Nullable<int> id_tecno_brick { get; set; }
        public Nullable<int> id_tecno_obj { get; set; }
    
        public virtual tecno_bricks tecno_bricks { get; set; }
        public virtual tecno_objs tecno_objs { get; set; }
    }
}
