//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class uni_budget
    {
        public int id_budget { get; set; }
        public string resource { get; set; }
        public Nullable<int> funded { get; set; }
        public Nullable<int> team { get; set; }
        public Nullable<double> scheduled { get; set; }
        public Nullable<double> actual { get; set; }
        public Nullable<System.DateTime> charge { get; set; }
        public Nullable<int> id_uni { get; set; }
        public Nullable<System.DateTime> charge_to { get; set; }
    
        public virtual master_uni master_uni { get; set; }
        public virtual site site { get; set; }
        public virtual teams teams { get; set; }
    }
}
